---
apiVersion: v1
kind: Service
metadata:
  name: follower
  labels:
    app: follower
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: follower
  type: LoadBalancer

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: follower
  name: follower
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: follower
  wildcardPolicy: None
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: follower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: follower
        name: follower
        role: follower
    spec:
      serviceAccountName: conjur-cluster
      containers:
      - name: conjur-appliance
        image: image-registry.openshift-image-registry.svc:5000/dap/conjur-appliance:11.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
