---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  conjur-map: |-   
    username: pas_dev/app/cityapp-safe/cityapp-db/username   
    password: pas_dev/app/cityapp-safe/cityapp-db/password
