---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-k8ssecret-init
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-k8ssecret-init
  labels:
    app: cityapp-k8ssecret-init
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-k8ssecret-init
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cityapp-k8ssecret-init
  name: cityapp-k8ssecret-init
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: cityapp-k8ssecret-init
  wildcardPolicy: None
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cityapp-k8ssecret-init
  name: cityapp-k8ssecret-init
spec:
  replicas: 1
  selector:
    app: cityapp-k8ssecret-init
  template:
    metadata:
      labels:
        app: cityapp-k8ssecret-init
    spec:
      serviceAccountName: cityapp-k8ssecret-init
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/cityapp/cityapp:1.0
          imagePullPolicy: Always
          name: cityapp-k8ssecret-init
          env:
            - name: DBAddress
              value: "mysql.cyber-ark-demo.local"
            - name: DBName
              value: "world"
            - name: DBPort
              value: "3306"
            - name: DBUsername
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DBPassword
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
      initContainers:
        - image: 'cyberark/secrets-provider-for-k8s'
          imagePullPolicy: Always
          name: authenticator
          env:
            - name: CONTAINER_MODE
              value: init
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: CONJUR_APPLIANCE_URL
              value: "https://dap-follower1.dap.svc.cluster.local/api"

            - name: CONJUR_AUTHN_URL
              value: "https://dap-follower1.dap.svc.cluster.local/api/authn-k8s/ocp"

            - name: CONJUR_ACCOUNT
              value: "CAU"

            - name: CONJUR_AUTHN_LOGIN
              value: "host/conjur/authn-k8s/ocp/apps/cityapp/*/*"

            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: follower-certificate
                  key: ssl-certificate

            - name: K8S_SECRETS
              value: db-credentials

            - name: SECRETS_DESTINATION
              value: k8s_secrets
