# conjur-role.yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-k8ssecret-init
---
apiVersion: v1
kind: RoleBinding
metadata:
  namespace: cityapp
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: cityapp
    name: cityapp-k8ssecret-init
roleRef:
  kind: ClusterRole
  name: secrets-access
---
apiVersion: v1
kind: ClusterRole
metadata:
  name: secrets-access
rules:
  - resources: ["secrets"]
    verbs: [ "get", "update" ]
