---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-openshiftsecret-01
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-openshiftsecret-01
  labels:
    app: cityapp-openshiftsecret-01
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-openshiftsecret-01
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cityapp-openshiftsecret-01
  name: cityapp-openshiftsecret-01
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: cityapp-openshiftsecret-01
  wildcardPolicy: None
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cityapp-openshiftsecret-01
  name: cityapp-openshiftsecret-01
spec:
  replicas: 1
  selector:
    app: cityapp-openshiftsecret-01
  template:
    metadata:
      labels:
        app: cityapp-openshiftsecret-01
    spec:
      serviceAccountName: cityapp-openshiftsecret-01
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cityapp/cityapp:1.0
        imagePullPolicy: Always
        name: cityapp
        env:
          - name: DBAddress
            value: "mysql.cyber-ark-demo.local"
          - name: DBName
            value: "world"
          - name: DBPort
            value: "3306"
          - name: DBUsername
            value: "cityapp-db01"
          - name: DBPassword
            valueFrom:
              secretKeyRef:
                name: cityapp-db01-secret
                key: password
        ports:
        - containerPort: 3000
          name: http
