---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-appid-d
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-appid-d
  labels:
    app: cityapp-appid-d
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-appid-d
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cityapp-appid-d
  name: cityapp-appid-d
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: cityapp-appid-d
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-appid-d
  name: cityapp-appid-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-appid-d
  template:
    metadata:
      labels:
        app: cityapp-appid-d
    spec:
      serviceAccountName: cityapp-appid-d
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cityapp/cityapp_with_summon:1.0
        imagePullPolicy: Always
        name: cityapp
        env:
          - name: CONJUR_APPLIANCE_URL
            value: "https://dap-follower1.dap.svc.cluster.local"
          - name: CONJUR_ACCOUNT
            value: "CAU"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: follower-certificate
                key: ssl-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
          - mountPath: /etc/summon
            name: summon-config
            readOnly: true
        command: [ "summon", "-f", "/etc/summon/secrets.yaml", "ruby", "/usr/src/cityapp_fromenv.rb", "-o", "0.0.0.0" ]
      initContainers:  # comment this line to troubleshoot authenticator container
      - image:  image-registry.openshift-image-registry.svc:5000/cityapp/conjur-kubernetes-authenticator:latest
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: CONTAINER_MODE
            value: init
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: "https://dap-follower1.dap.svc.cluster.local"
          - name: CONJUR_AUTHN_URL
            value: "https://dap-follower1.dap.svc.cluster.local/authn-k8s/ocp"
          - name: CONJUR_ACCOUNT
            value: "CAU"
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/ocp/apps/cityapp/deployment/cityapp-appid-d"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: follower-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: summon-config
          configMap:
            name: cityapp-appid-config

