---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-api-sidecar
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-api-sidecar
  labels:
    app: cityapp-api-sidecar
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-api-sidecar
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cityapp-api-sidecar
  name: cityapp-api-sidecar
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: cityapp-api-sidecar
  wildcardPolicy: None

---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cityapp-api-sidecar
  name: cityapp-api-sidecar
spec:
  replicas: 1
  selector:
    app: cityapp-api-sidecar
  template:
    metadata:
      labels:
        app: cityapp-api-sidecar
    spec:
      serviceAccountName: cityapp-api-sidecar
      containers:
      - image: "image-registry.openshift-image-registry.svc:5000/cityapp/cityapp_api:1.0"
        imagePullPolicy: Always
        name: cityapp
        env:
          - name: DBAddress
            value: "mysql.cyber-ark-demo.local"
          - name: DBPort
            value: "3306"
          - name: DBName
            value: "world"
          - name: DBPassword_CONJUR_VAR
            value: "pas_dev/app/cityapp-safe/cityapp-db/password"
          - name: DBUsername_CONJUR_VAR
            value: "pas_dev/app/cityapp-safe/cityapp-db/username"
          - name: CONJUR_APPLIANCE_URL
            value: "https://dap-follower1.dap.svc.cluster.local/api"
          - name: CONJUR_ACCOUNT
            value: CAU
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: follower-certificate
                key: ssl-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_VERSION
            value: "5"
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
#      - image: cyberark/conjur-kubernetes-authenticator
      - image: image-registry.openshift-image-registry.svc:5000/cityapp/conjur-kubernetes-authenticator:latest
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_VERSION
            value: '5'
          - name: CONJUR_APPLIANCE_URL
            value: "https://dap-follower1.dap.svc.cluster.local/api"
          - name: CONJUR_AUTHN_URL
            value: "https://dap-follower1.dap.svc.cluster.local/api/authn-k8s/ocp"
          - name: CONJUR_ACCOUNT
            value: CAU
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/ocp/apps/cityapp/*/*"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: follower-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
